name: Build

on:
  # Build on new commits or pull requests.
  push:
  pull_request:
  schedule:
    # Run every week just to make sure the CI environment still works.
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      # Install 6.0 for the mautil command
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Merge translations into add-in manifest
      run: dotnet run --project Pinta/installer/addins/Pinta.AddinUtils.csproj -- localize-manifest --manifest-file BlockBrush/.addin.xml --resource-files BlockBrush/Resources/*.resx
    - name: Compile
      run: dotnet build -c Release
    - name: Install mautil
      run: dotnet tool install --global Mono.Addins.UtilTool
    - name: Create Package
      run: mautil pack BlockBrush/bin/Release/net8.0/BlockBrush.dll
    - name: Upload Package
      uses: actions/upload-artifact@v5
      with:
        path: '*.mpack'
        if-no-files-found: error
